task:
  _target_: raptgfn.tasks.simple_dna.SimpleDNATask
  objectives:
  - length
  - gc_content
  eval_pref:
  - 0.5
  - 0.5
  score_max:
  - 1.0
  - 1.0
  regex_list: null
  min_len: 30
  max_len: 60
  ideal_length: 45
  ideal_gc_content: 0.5
  num_start_examples: 512
  batch_size: 16
  max_num_edits: null
  max_ngram_size: 1
  allow_len_change: true
  max_score_per_dim: 16
algorithm:
  _target_: raptgfn.algorithms.mogfn.MOGFN
  _recursive_: false
  train_steps: 10
  batch_size: 128
  pi_lr: 0.0001
  z_lr: 0.001
  wd: 0.0001
  max_len: 60
  min_len: 30
  random_action_prob: 0.01
  sampling_temp: 1.0
  gen_clip: 10
  reward_min: 1.0e-80
  reward_max: 100
  reward_type: convex
  beta_use_therm: true
  pref_use_therm: true
  beta_cond: true
  pref_cond: true
  beta_scale: 1
  beta_shape: 32
  pref_alpha: 1.0
  beta_max: 32
  therm_n_bins: 50
  sample_beta: 4
  eval_metrics:
  - hypervolume
  - r2
  - hsri
  eval_freq: 5
  num_samples: 256
  k: 10
  simplex_bins: 10
  use_eval_pref: false
  num_pareto_points: 500
  pareto_freq: 200
  unnormalize_rewards: false
  state_save_path: ./outputs/mogfn_state.pkl.gz
  model:
    _target_: raptgfn.algorithms.conditional_transformer.CondGFNTransformer
    max_len: 60
    vocab_size: 10
    num_actions: 5
    num_hid: 64
    num_layers: 3
    num_head: 8
    bidirectional: false
    dropout: 0.0
    batch_size: 128
tokenizer:
  _target_: raptgfn.utils.AptamerTokenizer
seed: 17368
trial_id: 0
project_name: raptgfn
version: v0.1.0
wandb_mode: disabled
data_dir: ./outputs
exp_name: dna_aptamer_experiment
group_name: aptamer_generation
exp_tags: []
job_name: aptamer_mogfn_0
timestamp: 2025-06-06_14-16-32
log_dir: ./outputs/dna_aptamer_experiment
