_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 13
                - 15
                - 16
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
config/algorithm/_recursive_:
    value: false
config/algorithm/_target_:
    value: dna_aptamer_mogfn.algorithms.mogfn.MOGFN
config/algorithm/batch_size:
    value: 64
config/algorithm/beta_cond:
    value: true
config/algorithm/beta_max:
    value: 32
config/algorithm/beta_scale:
    value: 1
config/algorithm/beta_shape:
    value: 32
config/algorithm/beta_use_therm:
    value: true
config/algorithm/eval_freq:
    value: 200
config/algorithm/eval_metrics:
    value:
        - hypervolume
        - r2
        - hsri
config/algorithm/gen_clip:
    value: 10
config/algorithm/k:
    value: 10
config/algorithm/max_len:
    value: 60
config/algorithm/min_len:
    value: 30
config/algorithm/model/_target_:
    value: dna_aptamer_mogfn.algorithms.conditional_transformer.CondGFNTransformer
config/algorithm/model/batch_size:
    value: 128
config/algorithm/model/bidirectional:
    value: false
config/algorithm/model/dropout:
    value: 0
config/algorithm/model/max_len:
    value: 60
config/algorithm/model/num_actions:
    value: 5
config/algorithm/model/num_head:
    value: 8
config/algorithm/model/num_hid:
    value: 64
config/algorithm/model/num_layers:
    value: 3
config/algorithm/model/vocab_size:
    value: 10
config/algorithm/num_pareto_points:
    value: 500
config/algorithm/num_samples:
    value: 256
config/algorithm/pareto_freq:
    value: 400
config/algorithm/pi_lr:
    value: 0.0001
config/algorithm/pref_alpha:
    value: 1
config/algorithm/pref_cond:
    value: true
config/algorithm/pref_use_therm:
    value: true
config/algorithm/random_action_prob:
    value: 0.01
config/algorithm/reward_max:
    value: 100
config/algorithm/reward_min:
    value: 1e-80
config/algorithm/reward_type:
    value: convex
config/algorithm/sample_beta:
    value: 4
config/algorithm/sampling_temp:
    value: 1
config/algorithm/simplex_bins:
    value: 10
config/algorithm/state_save_path:
    value: ./outputs/mogfn_state.pkl.gz
config/algorithm/therm_n_bins:
    value: 50
config/algorithm/train_steps:
    value: 2000
config/algorithm/unnormalize_rewards:
    value: false
config/algorithm/use_eval_pref:
    value: false
config/algorithm/wd:
    value: 0.0001
config/algorithm/z_lr:
    value: 0.001
config/data_dir:
    value: ./outputs
config/exp_name:
    value: dna_aptamer_training_20250605_202729_length_gc
config/exp_tags:
    value: []
config/group_name:
    value: aptamer_generation
config/job_name:
    value: null
config/log_dir:
    value: ./outputs/dna_aptamer_training_20250605_202729_length_gc
config/project_name:
    value: dna_aptamer_mogfn
config/seed:
    value: 42
config/task/_target_:
    value: dna_aptamer_mogfn.tasks.simple_dna.SimpleDNATask
config/task/allow_len_change:
    value: true
config/task/batch_size:
    value: 16
config/task/eval_pref:
    value:
        - 0.5
        - 0.5
config/task/ideal_gc_content:
    value: 0.5
config/task/ideal_length:
    value: 45
config/task/max_len:
    value: 60
config/task/max_ngram_size:
    value: 1
config/task/max_num_edits:
    value: null
config/task/max_score_per_dim:
    value: 16
config/task/min_len:
    value: 30
config/task/num_start_examples:
    value: 512
config/task/objectives:
    value:
        - length
        - gc_content
config/task/regex_list:
    value: null
config/task/score_max:
    value:
        - 1
        - 1
config/timestamp:
    value: 2025-06-05_20-27-34
config/tokenizer/_target_:
    value: dna_aptamer_mogfn.utils.AptamerTokenizer
config/trial_id:
    value: 0
config/version:
    value: v0.1.0
config/wandb_mode:
    value: online
