# 簡単なDNAタスク設定: 塩基バランス + 多様性
_target_: raptgfn.tasks.simple_dna.SimpleDNATask
objectives:
  - base_balance
  - dinucleotide_diversity
eval_pref: 
  - 0.5
  - 0.5
score_max:
  - 1.0    # 塩基バランススコアの最大値
  - 1.0    # 多様性スコアの最大値
regex_list: null
min_len: 30
max_len: 60
ideal_length: 45
ideal_gc_content: 0.5
num_start_examples: 512
batch_size: 16
max_num_edits: null
max_ngram_size: 1
allow_len_change: true
max_score_per_dim: 16
