# 簡単なDNAタスク設定: 3つの目的関数
_target_: dna_aptamer_mogfn.tasks.simple_dna.SimpleDNATask
objectives:
  - length
  - gc_content
  - complexity
eval_pref: 
  - 0.4
  - 0.3
  - 0.3
score_max:
  - 1.0    # 長さスコアの最大値
  - 1.0    # GC含有量スコアの最大値
  - 1.0    # 複雑さスコアの最大値
regex_list: null
min_len: 30
max_len: 60
ideal_length: 45
ideal_gc_content: 0.5
num_start_examples: 512
batch_size: 16
max_num_edits: null
max_ngram_size: 1
allow_len_change: true
max_score_per_dim: 16
