# 簡単なDNAタスク設定: 配列長 + GC含有量
_target_: raptgfn.tasks.simple_dna.SimpleDNATask
objectives:
  - length
  - gc_content
eval_pref: 
  - 0.5
  - 0.5
score_max:
  - 1.0    # 長さスコアの最大値
  - 1.0    # GC含有量スコアの最大値
regex_list: null
min_len: 30
max_len: 60
ideal_length: 45  # 理想的な配列長
ideal_gc_content: 0.5  # 理想的なGC含有量 (50%)
num_start_examples: 512
batch_size: 16
max_num_edits: null
max_ngram_size: 1
allow_len_change: true
max_score_per_dim: 16
